spring:
  datasource:
    hikari:
      max-lifetime: 3600
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333
    url: jdbc:mysql://adp.zoons.top:3306/adp?useUnicode=true&characterEncoding=utf8
pebble:
  suffix: .html
server:
  port: 8081