spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333
    url: jdbc:mysql://43.143.23.30:3306/adp
  redis:
    database: 0
    host: 43.143.23.30
    port: 6379
    password: 333