spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333
    url: jdbc:mysql://43.143.23.30:3306/adp?useUnicode=true&characterEncoding=utf8
    hikari:
      connection-timeout: 3600
#  redis:
#    database: 0
#    host: 43.143.23.30
#    port: 6379
#    password: 333
#    url: redis://333@43.143.23.30:6379